name: AutoInv
main: JackNoordhuis\AutoInv\AutoInvLoader
src-namespace-prefix: JackNoordhuis\AutoInv
author: JackNoordhuis
description: Limit the amount of item entities on your server by adding them straight to player inventories
version: 1.0.0
api: [4.0.0]
