name: AutoInv
author: JackNoordhuis
description: Limits the amount of item entities in your server by adding item drops straight to entities inventories
version: 0.0.8
main: jacknoordhuis\autoinv\AutoInv
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]