name: AutoInv
author: JackNoordhuis
description: Limits the amount of item entities in your server by adding item drops straight to entities inventories
version: 0.0.10
main: jacknoordhuis\autoinv\AutoInv
api: 3.14
