name: phpstan

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04 # pmmp-php-build doesn't work on ubuntu-latest yet

    steps:
    - uses: actions/checkout@v3
    - uses: nxtlvlsoftware/run-phpstan-pmmp-action@v1
      with:
        pmmp-version: 3.28.0
